export const environment = {
  production: false,
  local: true,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  API_ENVIRONMENT: 'local',
  STRIPE_LIFETIME_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_aEU8zJdFu6cofrq5ko',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_5kAbLV1WM9oAcfe9AG',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_cN2dU358Y7gscfe5kp',
  FRONT_END_URL: 'http://localhost:4200',
  MAIN_API_URL: 'http://localhost:4200/api',
  SUPABASE_URL: 'https://auth.releaseminder.io',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYXd3YWp5d2xoY2Jhd3hpenJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc0MDM3MDIsImV4cCI6MjA0Mjk3OTcwMn0.sKs-_ZaXBsjPw2O8xJAgnAua1JVQpbs4BG54PKpbuw8',
  FLAGSMITH_CLIENT_SDK_KEY: '2eYv7n2m9yomhZkLFzRax5',
  FLAGSMITH_API_URL: 'https://flagsmith.production.releaseminder.io/api/v1/',
  PAYMENTS_SERVICE_BASE_URL: 'v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'v1/application-messages',
  USERS_SERVICE_BASE_URL: 'v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'v1/ledgers/expenses',
};
