export const environment = {
  production: true,
  local: false,
  SNACKBAR_DURATION_MS: 5000,
  TOAST_DURATION_MS: 5000,
  API_ENVIRONMENT: 'staging',
  STRIPE_LIFETIME_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_fZeg2b7h6dEQgvu7sv',
  STRIPE_MONTHLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_eVaaHR30Q6co1AA5kl',
  STRIPE_ANNUALLY_PAYMENT_URL: 'https://checkout.roomyledger.com/b/test_bIY7vFgRGfMYbbacMO',
  FRONT_END_URL: 'https://staging.roomyledger.com',
  MAIN_API_URL: 'https://api.staging.roomyledger.com/v1',
  SUPABASE_URL: 'https://auth.releaseminder.io',
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYXd3YWp5d2xoY2Jhd3hpenJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc0MDM3MDIsImV4cCI6MjA0Mjk3OTcwMn0.sKs-_ZaXBsjPw2O8xJAgnAua1JVQpbs4BG54PKpbuw8',
  FLAGSMITH_CLIENT_SDK_KEY: '2eYv7n2m9yomhZkLFzRax5',
  FLAGSMITH_API_URL: 'https://flagsmith.production.releaseminder.io/api/v1/',
  LOGIN_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/users',
  PAYMENTS_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/payments',
  APPLICATION_MESSAGES_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/application-messages',
  USERS_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/users',
  NOTIFICATIONS_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/notifications',
  PROPERTIES_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/ledgers/properties',
  EXPENSES_SERVICE_BASE_URL: 'https://api.staging.roomyledger.com/v1/ledgers/expenses',
};
