FROM --platform=linux/amd64 node:20.17.0-alpine3.20 As development

WORKDIR /usr/src/app

COPY --chown=node:node package.json ./
COPY --chown=node:node pnpm-lock.yaml ./

RUN npm install -g pnpm@9.12.1

RUN pnpm install --frozen-lockfile

COPY --chown=node:node . .

USER node

FROM --platform=linux/amd64 node:20.17.0-alpine3.20 As build

WORKDIR /usr/src/app

COPY --chown=node:node package.json ./
COPY --chown=node:node pnpm-lock.yaml ./

COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules

COPY --chown=node:node . .

RUN npm install -g pnpm@9.12.1

ARG SERVICE_NAME="api"

RUN pnpm run build:${SERVICE_NAME}

ENV NODE_ENV production

USER node

FROM --platform=linux/amd64 node:20.17.0-alpine3.20 As production

COPY --chown=node:node --from=build /usr/src/app/package.json ./package.json
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist

RUN npm install -g pnpm@9.12.1

ENV SERVICE_NAME="api"

EXPOSE 8080

CMD [ "sh", "-c", "pnpm run start:prod:${SERVICE_NAME}" ]
